SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `book`
--
CREATE SCHEMA IF NOT EXISTS  `order` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `order`;

CREATE TABLE orders (
OID INT  primary key AUTO_INCREMENT,
PID INT  ,
Quantity INT,
CID INT,
Date_time TIMESTAMP,
OStatus INT,
DStatus VARCHAR (128),
PResponse VARCHAR (128)
);


